var maxDownload={};
maxDownload.categoryIdList={incomplete:"14",completed:"12",all:"10",deleted:"3",search:"10"};
maxDownload.defaultCategory="incomplete",maxDownload.updateFreq=1000;
maxDownload.fatalError=false;
maxDownload.taskList=[];
maxDownload.itemCount=0;
maxDownload.pageSize=12;
maxDownload.currentPage=1;
maxDownload.checkedIDList={};
maxDownload.checkedCount=0;
$langDefaultSection="Downloader";
maxDownload.init=function(){document.title=$lang("title");
maxDownload.initObject();
maxDownload.buildTaskList();
maxDownload.adjustHeight();
window.onresize=maxDownload.adjustHeight;
var A=$cookies("mxDownload_activePage");
if(maxDownload.categoryIdList[A]){maxDownload.defaultCategory=A}maxDownload.currentCategory=maxDownload.defaultCategory;
maxDownload.activateCategory(maxDownload.defaultCategory);
maxDownload.dataUpdater()};
maxDownload.initObject=function(){try{maxDownload.objDownload=new ActiveXObject("MxDownloadServer.ThunderMx.1")}catch(A){maxDownload.msgObjectError()}};
maxDownload.msgObjectError=function(){maxDownload.fatalError=true;
var A=$id("errorMessage");
A.style.display="block";
A.innerHTML=$lang("download_object_fail").$encodeHTML()+' &nbsp; <a href="javascript:;" onclick="maxDownload.reload()">'+$lang("download_object_fail_retry").$encodeHTML()+"</a>"};
maxDownload.reload=function(){maxDownload.fatalError=false;
$id("errorMessage").style.display="none";
maxDownload.initObject();
maxDownload.dataUpdater()};
maxDownload.showSettings=function(){try{maxDownload.objDownload.ShowSetting()}catch(A){maxDownload.msgObjectError()}};
maxDownload.activateCategory=function(B){if(maxDownload.currentCategory=="search"){maxDownload.resetSearch();
var A=$id("searchButton");
A.src="images/search.png";
A.onclick=maxDownload.updateTaskList}maxDownload.switchCategoryUI(B);
if(B=="incomplete"||B=="all"){$cookies("mxDownload_activePage",B)}maxDownload.updateTaskList()};
maxDownload.switchCategoryUI=function(B){if(!maxDownload.categoryIdList[B]){alert('maxDownload.activateCategory :: invalid type "'+B+'"')}var A="";
var C="buttons-active";
if(B=="search"){C="label buttons-active"}if(maxDownload.currentCategory=="search"){A="label"}$id("page_"+maxDownload.currentCategory).className=A;
$id("page_"+B).className=C;
if(B!="search"){$id("num_"+B).className=""}if(B=="search"||B=="deleted"||B=="completed"){$id("ucontrol").style.display="none"}else{$id("ucontrol").style.display="inline"}if(B=="deleted"){$id("emptybin").style.display="inline"}else{$id("emptybin").style.display="none"}maxDownload.currentCategory=B;
maxDownload.currentPage=1};
maxDownload.resetSearch=function(A){$id("searchBar").value=""};
maxDownload.dataUpdater=function(){if(maxDownload.fatalError){return}var B=$id("searchBar").value;
var C=false;
B=B.$trim();
var A=$id("searchButton");
if(B!=""){A.src="images/reset.png";
A.onclick=maxDownload.resetSearch;
maxDownload.switchCategoryUI("search")}else{B=false;
if(maxDownload.currentCategory=="search"){maxDownload.activateCategory(maxDownload.defaultCategory)}}maxDownload.updateCounter();
maxDownload.updateTaskList(B);
setTimeout(maxDownload.dataUpdater,maxDownload.updateFreq)};
maxDownload.lastCounter=[-1,-1,-1,-1];
maxDownload.updateCounter=function(){var B=[];
try{B=maxDownload.objDownload.GetTaskCount2("14{\r\r*\r\r}12{\r\r*\r\r}10{\r\r*\r\r}3")}catch(E){maxDownload.msgObjectError();
return}B=B.split("{\r\r*\r\r}");
var A=[];
for(var C=0;
C<B.length;
C++){var F=B[C];
if(F.length<1){continue}F=F.split("{\r*\r}");
A.push(F[1])}var D=["num_incomplete","num_completed","num_all","num_deleted"];
for(var C=0;
C<A.length;
C++){if(A[C]!=0){$id(D[C]).innerHTML="("+A[C]+")"}else{$id(D[C]).innerHTML=""}if(maxDownload.lastCounter[C]>-1){if(A[C]>maxDownload.lastCounter[C]){$id(D[C]).className="num-highlight"}}}maxDownload.lastCounter=A};
maxDownload.buildTaskList=function(){downloadTable=maxTable.create("downloadTable");
downloadTable.controlUI["delete"]=$lang("delete");
downloadTable.controlUI.cancel=$lang("cancel");
downloadTable.controlUI.checkbox='<img src="../_shared/images/btn_check.png" />';
downloadTable.controlUI.checkbox_checked='<img src="../_shared/images/btn_check_checked.png" />';
downl
oadTable.controlUI.move_up='<img src="../_shared/images/btn_up.png" />';
downloadTable.controlUI.move_down='<img src="../_shared/images/btn_down.png" />';
downloadTable.columns=[{title:'<div onclick="maxDownload.checkAll()" style="cursor:pointer"><img id="btnCheckAll" src="../_shared/images/btn_check.png" /></div>',name:"checked",type:"checkbox",width:18},{title:"&nbsp;",name:"status",type:"custom",width:18,customBuilder:maxDownload.buildItemHTML},{title:$lang("filename"),name:"fileName",type:"custom",customBuilder:maxDownload.buildItemHTML},{title:$lang("size"),name:"size",type:"custom",width:100,customBuilder:maxDownload.buildItemHTML},{title:$lang("progress"),name:"percent",type:"custom",width:150,customBuilder:maxDownload.buildItemHTML},{title:$lang("time_used"),name:"timeUsed",type:"custom",width:120,customBuilder:maxDownload.buildItemHTML}];
downloadTable.dataType="object";
downloadTable.data=maxDownload.taskList;
downloadTable.showEditControl=false;
downloadTable.allowEditSeparator=false;
downloadTable.allowInsert=false;
downloadTable.confirmDelete=false;
downloadTable.tableTag=' width="100%" cellpadding="0" cellspacing="0" border="0"',downloadTable.editControl=[{type:"delete",hideOnNew:true},{type:"html",value:" | ",hideOnNew:true},{type:"cancel"}];
downloadTable.lang.delete_confirm=$lang("confirm_delete_task");
downloadTable.event.beforeDelete=maxDownload.deleteTask;
downloadTable.event.afterCheckboxClick=maxDownload.checkItem;
maxTable.init(downloadTable)};
maxDownload.adjustHeight=function(){var B=$id("contentWrapper");
if(!B){return}var A=document.documentElement.clientHeight-160;
B.style.height=A-10};
maxDownload.buildItemHTML=function(H,E){var F=downloadTable.data[H];
var A="";
if(E==1){if(F.status<2){A='<a href="javascript:;" onclick="maxDownload.stopTask(\''+F.id+'\')"><img src="images/check.png" alt="'+$lang("status_check")+'"/></a>'}else{if(F.status==2){A='<a href="javascript:;" onclick="maxDownload.stopTask(\''+F.id+'\')"><img src="images/run.png" alt="'+$lang("status_run")+'" /></a>'}else{if(F.status==10){A='<a href="javascript:;" onclick="maxDownload.startTask(\''+F.id+'\')"><img src="images/pause.png" alt="'+$lang("status_pause")+'" /></a>'}else{if(F.status==11){A='<a href="javascript:;" onclick="maxDownload.restartTask(\''+F.id+'\')"><img src="images/done.png" alt="'+$lang("status_done")+'" /></a>'}else{A='<a href="javascript:;" onclick="maxDownload.startTask(\''+F.id+'\')"><img src="images/error.png" alt="'+$lang("status_error")+'" /></a>'}}}}}else{if(E==2){if(downloadTable.inAction=="edit"&&downloadTable.inEditDataIndex==H){var D=maxDownload.getTaskDetail(F.id);
A="<strong>"+F.fileName.$encodeHTML()+"</strong>";
A+=maxDownload.buildEditControlHTML()}else{A+='<span style="float:right">';
if(F.status==11){A+='<a href="javascript:;" onclick="maxDownload.openFile(\''+F.id+"');event.cancelBubble=true;\">"+$lang("open")+"</a> &nbsp;"}A+='<a href="javascript:;" onclick="maxDownload.openTaskFolder(\''+F.id+"');event.cancelBubble=true;\">"+$lang("o_folder")+"</a>";
A+="</span>";
A+=F.fileName.$encodeHTML().$cut(50)}}else{if(E==3){A=maxDownload.fileSizeString(F.size)}else{if(E==4){var B;
if(F.status<2){B=" progressBarStop"}else{if(F.status==2){B=""}else{if(F.status==10){B=" progressBarStop"}else{if(F.status==11){B=" progressBarDone"}else{B=" progressBarError"}}}}A+='<div class="progressBarOuter" style="width:100%">';
if(F.status==2){A+='<div class="speed">'+maxDownload.speedString(F.speed)+"</div>"}A+='<div class="progressBar'+B+'" style="width:'+Math.floor(100*F.progress)+'%;">&nbsp;'+maxDownload.progressString(F.progress)+"</div>";
A+="</div>"}else{if(E==5){var C=maxDownload.timeString(F.timeUsed);
if(C==""){C="00:00:00"}var G=maxDownload.timeString(F.timeLeft);
A=C+(G!=""?' <span class="timeLeft">('+G+")</span>":"")}}}}}return A};
maxDownload.fileSizeString=function(B){var A=B;
if(isNaN(A)){return"0"}if(A==0){return"0"}var C="Bytes";
if((A/1073741824)>1){A=(A/1073741824).toString();
C="GB"}else{if((A/1048576)>1){A=(A/1048576).toString();
C="MB"}else{if((A/1024)>1){A=(A/1024).toString();
C="KB"}else{A=A.toString();
C="Bytes"}}}if(A.indexOf
(".")>-1){A=A.substr(0,A.indexOf(".")+2)}return A+" "+C};
maxDownload.speedString=function(B){var C=B;
if(isNaN(C)){return"0"}if(C==0){return"0"}var A="Bytes";
if((C/1073741824)>1){C=(C/1073741824).toString();
A="GB/s"}else{if((C/1048576)>1){C=(C/1048576).toString();
A="MB/s"}else{if((C/1024)>1){C=(C/1024).toString();
A="KB/s"}else{C=C.toString();
A="B/s"}}}if(C.indexOf(".")>-1){C=C.substr(0,C.indexOf(".")+2)}return C+" "+A};
maxDownload.progressString=function(A){var B=A;
if(isNaN(B)){return"0"}B=(B*100).toString();
if(B.length>5){B=B.substr(0,5)}B+="%";
return B};
maxDownload.timeString=function(D){if(D<1){return""}var C=Math.floor(D/3600).toString();
if(C.length==1){C="0"+C}var A=Math.floor((D%3600)/60).toString();
if(A.length==1){A="0"+A}var B=(D%60).toString();
if(B.length==1){B="0"+B}return C+":"+A+":"+B};
maxDownload.buildEditControlHTML=function(){var B=downloadTable.data[downloadTable.inEditDataIndex];
var A='<p class="inline-control">';
if(B.status==10||B.status==12){A+='<a href="javascript:;" onclick="maxDownload.startTask(\''+B.id+"')\">"+$lang("start")+"</a> | "}if(B.status<=2){A+='<a href="javascript:;" onclick="maxDownload.stopTask(\''+B.id+"')\">"+$lang("stop")+"</a> | "}if(B.status==11){A+='<a href="javascript:;" onclick="maxDownload.openFile(\''+B.id+"')\">"+$lang("open_file")+"</a> | "}A+='<a href="javascript:;" onclick="maxDownload.openTaskFolder(\''+B.id+"')\">"+$lang("open_folder")+"</a> | ";A+='<a href="javascript:;" onclick="maxTable.action.deleteEdit('+downloadTable.objID+')">'+downloadTable.controlUI["delete"]+"</a> | ";if(B.status==11){A+='<a href="javascript:;" onclick="maxDownload.restartTask(\''+B.id+"')\">"+$lang("restart")+"</a> | "}A+='<a href="javascript:;" onclick="maxDownload.showTaskProperties(\''+B.id+"')\">"+$lang("show_prop")+"</a> | ";
A+='<a href="javascript:;" onclick="maxTable.action.cancelEdit('+downloadTable.objID+')">'+downloadTable.controlUI.cancel+"</a>";
A+="</p>";
return A};
maxDownload.loadTaskList=function(D){var F;
try{if(D){F=maxDownload.objDownload.SearchTaskList("10="+D,(maxDownload.currentPage-1)*maxDownload.pageSize,maxDownload.pageSize,0)}else{F=maxDownload.objDownload.GetTaskList(maxDownload.categoryIdList[maxDownload.currentCategory],(maxDownload.currentPage-1)*maxDownload.pageSize,maxDownload.pageSize,0)}}catch(E){maxDownload.msgObjectError();
return[]}F=F.split("{\r\r*\r\r}");
var A={};
var G=0;
var J=[];
for(var B=0;
B<F.length;
B++){var H=F[B];
if(H.length<10){continue}H=H.split("{\r*\r}");
var I={};
I.id=H[1];
I.tag=H[3];
I.status=parseInt(H[4],10);
I.speed=parseInt(H[5],10);
I.progress=parseFloat(H[6]);
I.size=parseInt(H[8],10);
I.timeUsed=parseInt(H[9],10);
I.timeLeft=parseInt(H[10],10);
I.createDate=H[11];
I.fileName=H[14];
I.fileExtension=H[15];
I.checked=(maxDownload.checkedIDList[I.id]==true)?true:false;
if(I.checked){A[I.id]=true;
G++}J.push(I)}var C=parseInt(F[0],10);
if(isNaN(C)){C=J.length}maxDownload.itemCount=C;
maxDownload.checkedIDList=A;
maxDownload.checkedCount=G;
return J};
maxDownload.getTaskDetail=function(D){var A={url:"",referer:"",folder:""};
var B;
try{B=maxDownload.objDownload.GetTaskInfo(D)}catch(C){maxDownload.msgObjectError()}B=B.split("{\r*\r}");
A.url=B[3];
A.referer=B[3];
A.folder=B[7];
return A};
maxDownload.updateTaskList=function(H){if(maxDownload.updatingTaskList){return}maxDownload.updatingTaskList=true;
var K=maxDownload.loadTaskList(H);
var E=maxDownload.taskList;
var G=K.length;
var B=E.length;
var C=G<B?G:B;
var I="";
var A=-1;
var F=false;
if(downloadTable.inAction=="edit"||downloadTable.inAction=="add"){var J=downloadTable.inEditDataIndex;
if(maxDownload.isEqualTask(K[J],E[J])){F=false;
A=D}else{if(E[J]){I=E[J].id}F=true}}for(var D=0;
D<C;
D++){if(maxDownload.isEqualTask(K[D],E[D])==false){E[D]=K[D];
maxTable.ui.updateRow(downloadTable,D)}}if(G>B){for(var D=B;
D<G;
D++){maxTable.ui.addRow(downloadTable,false,K[D])}}if(G<B){for(var D=G;
D<B;
D++){maxTable.ui.deleteRow(downloadTable,G)}}maxDownload.updateCheckAllUI();
maxDownload.updateStats();
maxDownload.updatePageLinks();
maxDownload.updatingTaskList=false};
maxDownload.isEqualTask=function(B,A){if(!B||!A){return false}if(B.checked!=A.checked
){return false}if(B.id!=A.id){return false}if(B.status!=A.status){return false}if(B.speed!=A.speed){return false}if(B.progress!=A.progress){return false}return true};
maxDownload.checkItem=function(C,A){var B=downloadTable.data[C];
if(B.checked){maxDownload.checkedIDList[B.id]=true;
maxDownload.checkedCount++}else{maxDownload.checkedIDList[B.id]=null;
maxDownload.checkedCount--}maxDownload.updateCheckAllUI()};
maxDownload.checkAll=function(){var C=false;
if(downloadTable.data.length!=maxDownload.checkedCount){C=true;
maxDownload.checkedCount=downloadTable.data.length}else{maxDownload.checkedCount=0}maxDownload.updateCheckAllUI();
for(var A=0;
A<downloadTable.data.length;
A++){var B=downloadTable.data[A];
if(B.checked!=C){maxDownload.checkedIDList[B.id]=C;
maxTable.ui.doCheckbox(downloadTable,A,0,C)}}};
maxDownload.updateCheckAllUI=function(){if(downloadTable.data.length!=maxDownload.checkedCount||maxDownload.checkedCount==0){$id("btnCheckAll").src="../_shared/images/btn_check.png"}else{$id("btnCheckAll").src="../_shared/images/btn_check_checked.png"}};
maxDownload.updateStats=function(){$id("stats").innerHTML=$lang("item_count").replace("%i",maxDownload.itemCount)};
maxDownload.updatePageLinks=function(){var B=$id("pagerWrapper");
var C="";
if(maxDownload.oldItemCount==maxDownload.itemCount&&maxDownload.oldCurrentPage==maxDownload.currentPage){return}maxDownload.oldItemCount=maxDownload.itemCount;
maxDownload.oldCurrentPage=maxDownload.currentPage;
if(maxDownload.itemCount>maxDownload.pageSize){var A={separator:"",normal:'<a href="javascript:maxDownload.setPage(%page);">%page</a>',active:'<a href="javascript:;" class="active">%page</a>',prev:'<a href="javascript:maxDownload.setPage(%page);">&#8249;</a>',next:'<a href="javascript:maxDownload.setPage(%page);">&#8250;</a>',first:'<a href="javascript:maxDownload.setPage(%page);">&laquo;</a>',last:'<a href="javascript:maxDownload.setPage(%page);">&raquo;</a>'};C=$pageLinks(maxDownload.itemCount,maxDownload.pageSize,maxDownload.currentPage,10,A);B.innerHTML=C;B.style.display="inline"}else{B.style.display="none"}};
maxDownload.setPage=function(A){maxTable.action.cancelEdit(downloadTable);
maxDownload.currentPage=A;
maxDownload.updateTaskList()};
maxDownload.addTask=function(){try{maxDownload.objDownload.CallAddTask("","","",0,"","")}catch(A){maxDownload.msgObjectError()}maxDownload.updateTaskList()};
maxDownload.deleteTask=function(B){var A;
try{A=maxDownload.objDownload.DeleteTask(B.id,0)}catch(C){maxDownload.msgObjectError()}if(A==0){return true;
maxDownload.updateTaskList()}else{return false}};
maxDownload.deleteSelected=function(){var D="";
for(var A=0;
A<downloadTable.data.length;
A++){var B=downloadTable.data[A];
if(B.checked!=true){continue}D+=B.id+"{\r*\r}"}if(D==""){return}try{maxDownload.objDownload.DeleteTask(D,0)}catch(C){maxDownload.msgObjectError();
return}maxDownload.updateTaskList()};
maxDownload.emptyBin=function(){try{maxDownload.objDownload.BatchDeleteTasks(3,0)}catch(A){maxDownload.msgObjectError();
return}};
maxDownload.startTask=function(B){try{maxDownload.objDownload.StartTask(B)}catch(A){maxDownload.msgObjectError()}maxDownload.cancelEventBubble();
maxDownload.updateTaskList()};
maxDownload.stopTask=function(B){try{maxDownload.objDownload.StopTask(B)}catch(A){maxDownload.msgObjectError()}maxDownload.cancelEventBubble();
maxDownload.updateTaskList()};
maxDownload.startAll=function(){try{maxDownload.objDownload.StartAll()}catch(A){maxDownload.msgObjectError()}maxDownload.updateTaskList()};
maxDownload.stopAll=function(){try{maxDownload.objDownload.StopAll()}catch(A){maxDownload.msgObjectError()}maxDownload.updateTaskList()};
maxDownload.restartTask=function(B){if(confirm($lang("confirm_restart"))){try{maxDownload.objDownload.DownloadAgain(B,1)}catch(A){maxDownload.msgObjectError()}maxDownload.updateTaskList()}maxDownload.cancelEventBubble()};
maxDownload.showTaskProperties=function(B){try{maxDownload.objDownload.ShowTaskProp(B)}catch(A){maxDownload.msgObjectError()}};
maxDownload.openFile=function(B){try{maxDownload.objDownload.OpenTaskFile(B)}catch(A){maxDownload.msgObjectError()}};
maxDownload.ope
nTaskFolder=function(B){try{maxDownload.objDownload.OpenTaskFolder(B)}catch(A){maxDownload.msgObjectError()}};
maxDownload.cancelEventBubble=function(){if(!window.event){return}window.event.cancelBubble=true;
window.event.returnValue=false};
